### ISSUE TITLE
Failure to export to graphml or cypher: ‘null’

### ISSUE THREAD

**Issue by equaeghe** [jexp/neo4j-shell-tools#101]
I have installed the shell tools as instructed and the commands it adds appear in the shell. However, when I try to export to cypher or graphml, I get an error:

```
$ neo4j-shell -v -c "export-cypher -o owfgraph.cql"
Wrote Nodes 0. 100%: nodes = 854 rels = 3071 properties = 0 time 29 ms total 29 ms
ERROR (-v for expanded information):
        null
java.util.NoSuchElementException
        at org.neo4j.helpers.collection.PrefetchingIterator.next(PrefetchingIterator.java:77)
        at org.neo4j.shell.kernel.ReadOnlyGraphDatabaseProxy$1$1.fetchNextOrNull(ReadOnlyGraphDatabaseProxy.java:173)
        at org.neo4j.shell.kernel.ReadOnlyGraphDatabaseProxy$1$1.fetchNextOrNull(ReadOnlyGraphDatabaseProxy.java:169)
        at org.neo4j.helpers.collection.PrefetchingIterator.peek(PrefetchingIterator.java:60)
        at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:46)
        at org.neo4j.shell.tools.imp.format.MultiStatementCypherSubGraphExporter.appendRelationships(MultiStatementCypherSubGraphExporter.java:194)
        at org.neo4j.shell.tools.imp.format.MultiStatementCypherSubGraphExporter.export(MultiStatementCypherSubGraphExporter.java:70)
        at org.neo4j.shell.tools.imp.ExportCypherApp.execute(ExportCypherApp.java:70)
        at org.neo4j.shell.impl.AbstractAppServer.interpretLine(AbstractAppServer.java:126)
        at org.neo4j.shell.kernel.GraphDatabaseShellServer.interpretLine(GraphDatabaseShellServer.java:105)
        at org.neo4j.shell.impl.RemotelyAvailableServer.interpretLine(RemotelyAvailableServer.java:60)
        at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
        at sun.rmi.transport.Transport$1.run(Transport.java:200)
        at sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

 -host      Domain name or IP of host to connect to (default: localhost)
 -port      Port of host to connect to (default: 1337)
 -name      RMI name, i.e. rmi://<host>:<port>/<name> (default: shell)
 -pid       Process ID to connect to
 -c         Command line to execute. After executing it the shell exits
 -file      File containing commands to execute, or '-' to read from stdin. After executing it the shell exits
 -readonly  Connect in readonly mode (only for connecting with -path)
 -path      Points to a neo4j db path so that a local server can be started there
 -config    Points to a config file when starting a local server

Example arguments for remote:
        -port 1337
        -host 192.168.1.234 -port 1337 -name shell
        -host localhost -readonly
        ...or no arguments for default values
Example arguments for local:
        -path /path/to/db
        -path /path/to/db -config /path/to/neo4j.config
        -path /path/to/db -readonly
```
The `dump` command works.

My configuration:
```
$neo4j-shell -v -c "dbinfo -g Configuration"                                 
{
  "dbms.allow_format_migration": "false",
  "dbms.backup.address": "127.0.0.1:6362-6372",
  "dbms.backup.enabled": "false",
  "dbms.connector.http.address": "localhost:7472",
  "dbms.connector.http.enabled": "true",
  "dbms.connector.http.type": "HTTP",
  "dbms.directories.import": "import",
  "dbms.mode": "HA",
  "dbms.read_only": "true",
  "dbms.security.auth_enabled": "false",
  "dbms.shell.enabled": "true",
  "dbms.shell.host": "127.0.0.1",
  "dbms.shell.port": "1337",
  "dbms.shell.read_only": "true",
  "dbms.shell.rmi_name": "shell",
  "dbms.udc.enabled": "true",
  "ha.host.coordination": "127.0.0.1:5002",
  "ha.host.data": "127.0.0.1:6002",
  "ha.initial_hosts": "127.0.0.1:5001,127.0.0.1:5002",
  "ha.pull_interval": "10",
  "ha.server_id": "2",
  "ha.slave_only": "true",
  "unsupported.dbms.directories.neo4j_home": "/home/owfgraph/ro/neo4j",
  "unsupported.dbms.edition": "enterprise",
  "unsupported.dbms.security.auth_store.location": "data/dbms/auth"
}
```

What could be the issue? What can I do to diagnose this further (I'm assuming it's an installation/configuration issue)?

**Comment by jexp** [comment]
Try to add a semicolon

neo4j-shell -v -c "export-cypher -o owfgraph.cql;"

**Comment by equaeghe** [comment]
> Try to add a semicolon
> 
> neo4j-shell -v -c "export-cypher -o owfgraph.cql;"

The semicolon makes no difference. I also tried the command in the shell itself, but that gives the same issue. I really have a feeling this is a configuration issue.

Whatever it is, as a workaround, would it be sensible to use the `dump` command, which does work? As in executing `neo4j-shell -v -c "dump match (n)-[r]->(m), (l) where not (l)--() return n, r, m, l;" > dump-.cql`. Would the dump be useful for restoring the database?

**Comment by jexp** [comment]
Dump is a very limited version of this.

it kinda looks like an issue with your data, can you run a consistency check?

Would you be able to share the database?

**Comment by equaeghe** [comment]
Ok, I did a consistency check (stripped timestamps):

```
$ java -cp 'lib/*:system/lib/*' org.neo4j.consistency.ConsistencyCheckTool data/databases/graph.db
INFO  [o.n.k.i.s.f.RecordFormatSelector] Format not configured. Selected format from the store: RecordFormat:StandardV3_0[v0.A.7]
```

initially everything's fine, but then I get

```
ERROR [o.n.c.ConsistencyCheckService] The relationship count does not correspond with the expected count.
    CountsEntry[RelationshipKey[(:label=3)-[:type=11]->()]: 28]
    Inconsistent with: 29
```

and 36 more of these, finally

```
ERROR [o.n.c.ConsistencyCheckService] The relationship key entries in the store does not correspond with the expected number.
    CountsEntry[RelationshipKey[()-->()]: 177]
    Inconsistent with: 161
WARN  [o.n.c.ConsistencyCheckService] Inconsistencies found: ConsistencySummaryStatistics{
    Number of errors: 37
    Number of warnings: 0
    Number of inconsistent COUNTS records: 37
}
```

I guess I'll have to fix those, try exporting again, and report back here. (Hints for fixing the consistency appreciated, I still have to read up on this.)

**Comment by equaeghe** [comment]
> I guess I'll have to fix those, try exporting again, and report back here.

This is a read-only slave and the master was consistent. So deleting the store and having it recreated from the master gave me a consistent store.

However, the error I reported initially is still there.

Regarding sharing the database: I'll have to hear around about that.

FWIW: This is a database that was upgraded from 2.3.6 community to 3.0.6 enterprise.

Regarding `dump`: in what way is it limited? I'm currently very interested in having a sufficiently good workaround. Is the dump output incomplete in some way (given the query `match (n)-[r]->(m), (l) where not (l)--() return n, r, m, l;`)? Is recreating the database from it not possible?

**Comment by equaeghe** [comment]
> This is a read-only slave and the master was consistent.

I tried it with the shell attached to the master and that works… I'm not going to dig into this further for now myself, given that I now have a working setup.
