### ISSUE TITLE
Error importing cypher statements with an exclamation point

### ISSUE THREAD

**Issue by telaviv** [jexp/neo4j-shell-tools#65]
```
sean@sean-laptop:~/opt/neo4j-community-2.3.0-M03$ ./bin/neo4j-shell -c < ~/Downloads/export-1.cypher > things.txt
[ERROR] Could not expand event
java.lang.IllegalArgumentException: !"], `current_rating`:[1468.9, 183.4, 0.1], `name`:"Had0uken!", `provisional_rating`:[1468.9, 183.7, 0.1], `ranked`:"unranked"});: event not found
    at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:779)
    at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:631)
    at jline.console.ConsoleReader.accept(ConsoleReader.java:2019)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2666)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2257)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.neo4j.shell.impl.JLineConsole.readLine(JLineConsole.java:98)
    at org.neo4j.shell.impl.AbstractClient.readLine(AbstractClient.java:268)
    at org.neo4j.shell.impl.AbstractClient.grabPrompt(AbstractClient.java:96)
    at org.neo4j.shell.StartClient.grabPromptOrJustExecuteCommand(StartClient.java:384)
    at org.neo4j.shell.StartClient.startRemote(StartClient.java:331)
    at org.neo4j.shell.StartClient.start(StartClient.java:196)
    at org.neo4j.shell.StartClient.main(StartClient.java:135)

[ERROR] Could not expand event
java.lang.IllegalArgumentException: !"], `current_rating`:[1261.7, 240, 0.1], `name`:"Yes!", `provisional_rating`:[1261.7, 240.2, 0.1], `ranked`:"unranked"});: event not found
    at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:779)
    at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:631)
    at jline.console.ConsoleReader.accept(ConsoleReader.java:2019)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2666)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2257)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.neo4j.shell.impl.JLineConsole.readLine(JLineConsole.java:98)
    at org.neo4j.shell.impl.AbstractClient.readLine(AbstractClient.java:268)
    at org.neo4j.shell.impl.AbstractClient.grabPrompt(AbstractClient.java:96)
    at org.neo4j.shell.StartClient.grabPromptOrJustExecuteCommand(StartClient.java:384)
    at org.neo4j.shell.StartClient.startRemote(StartClient.java:331)
    at org.neo4j.shell.StartClient.start(StartClient.java:196)
    at org.neo4j.shell.StartClient.main(StartClient.java:135)

[ERROR] Could not expand event
java.lang.IllegalArgumentException: !"], `current_rating`:[1615.3, 191.3, 0.1], `name`:"Mah!", `provisional_rating`:[1615.3, 191.6, 0.1], `ranked`:"unranked"});: event not found
    at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:779)
    at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:631)
    at jline.console.ConsoleReader.accept(ConsoleReader.java:2019)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2666)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2257)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.neo4j.shell.impl.JLineConsole.readLine(JLineConsole.java:98)
    at org.neo4j.shell.impl.AbstractClient.readLine(AbstractClient.java:268)
    at org.neo4j.shell.impl.AbstractClient.grabPrompt(AbstractClient.java:96)
    at org.neo4j.shell.StartClient.grabPromptOrJustExecuteCommand(StartClient.java:384)
    at org.neo4j.shell.StartClient.startRemote(StartClient.java:331)
    at org.neo4j.shell.StartClient.start(StartClient.java:196)
    at org.neo4j.shell.StartClient.main(StartClient.java:135)

[ERROR] Could not expand event
java.lang.IllegalArgumentException: !"], `current_rating`:[1596.9, 175.5, 0.1], `name`:"Three!", `provisional_rating`:[1596.9, 175.9, 0.1], `ranked`:"unranked"});: event not found
    at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:779)
    at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:631)
    at jline.console.ConsoleReader.accept(ConsoleReader.java:2019)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2666)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2257)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.neo4j.shell.impl.JLineConsole.readLine(JLineConsole.java:98)
    at org.neo4j.shell.impl.AbstractClient.readLine(AbstractClient.java:268)
    at org.neo4j.shell.impl.AbstractClient.grabPrompt(AbstractClient.java:96)
    at org.neo4j.shell.StartClient.grabPromptOrJustExecuteCommand(StartClient.java:384)
    at org.neo4j.shell.StartClient.startRemote(StartClient.java:331)
    at org.neo4j.shell.StartClient.start(StartClient.java:196)
    at org.neo4j.shell.StartClient.main(StartClient.java:135)

[ERROR] Could not expand event
java.lang.IllegalArgumentException: !"], `current_rating`:[1602.6, 95.4, 0.1], `name`:"Serg!", `provisional_rating`:[1602.6, 96, 0.1], `ranked`:"unranked"});: event not found
    at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:779)
    at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:631)
    at jline.console.ConsoleReader.accept(ConsoleReader.java:2019)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2666)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2257)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.neo4j.shell.impl.JLineConsole.readLine(JLineConsole.java:98)
    at org.neo4j.shell.impl.AbstractClient.readLine(AbstractClient.java:268)
    at org.neo4j.shell.impl.AbstractClient.grabPrompt(AbstractClient.java:96)
    at org.neo4j.shell.StartClient.grabPromptOrJustExecuteCommand(StartClient.java:384)
    at org.neo4j.shell.StartClient.startRemote(StartClient.java:331)
    at org.neo4j.shell.StartClient.start(StartClient.java:196)
    at org.neo4j.shell.StartClient.main(StartClient.java:135)

[ERROR] Could not expand event
java.lang.IllegalArgumentException: !"], `current_rating`:[1639.6, 185.9, 0.1], `name`:"GiGa | Surg!", `provisional_rating`:[1639.6, 186.2, 0.1], `ranked`:"unranked"});: event not found
    at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:779)
    at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:631)
    at jline.console.ConsoleReader.accept(ConsoleReader.java:2019)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2666)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2257)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.neo4j.shell.impl.JLineConsole.readLine(JLineConsole.java:98)
    at org.neo4j.shell.impl.AbstractClient.readLine(AbstractClient.java:268)
    at org.neo4j.shell.impl.AbstractClient.grabPrompt(AbstractClient.java:96)
    at org.neo4j.shell.StartClient.grabPromptOrJustExecuteCommand(StartClient.java:384)
    at org.neo4j.shell.StartClient.startRemote(StartClient.java:331)
    at org.neo4j.shell.StartClient.start(StartClient.java:196)
    at org.neo4j.shell.StartClient.main(StartClient.java:135)

[ERROR] Could not expand event
java.lang.IllegalArgumentException: !"], `current_rating`:[1777.7, 180, 0.1], `name`:"GiGa | Surge!", `provisional_rating`:[1777.7, 180.3, 0.1], `ranked`:"unranked"});: event not found
    at jline.console.ConsoleReader.expandEvents(ConsoleReader.java:779)
    at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:631)
    at jline.console.ConsoleReader.accept(ConsoleReader.java:2019)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2666)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
    at jline.console.ConsoleReader.readLine(ConsoleReader.java:2257)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.neo4j.shell.impl.JLineConsole.readLine(JLineConsole.java:98)
    at org.neo4j.shell.impl.AbstractClient.readLine(AbstractClient.java:268)
    at org.neo4j.shell.impl.AbstractClient.grabPrompt(AbstractClient.java:96)
    at org.neo4j.shell.StartClient.grabPromptOrJustExecuteCommand(StartClient.java:384)
    at org.neo4j.shell.StartClient.startRemote(StartClient.java:331)
    at org.neo4j.shell.StartClient.start(StartClient.java:196)
    at org.neo4j.shell.StartClient.main(StartClient.java:135)
```

Seems like any statement with an exclamation point causes an error.

```
```

**Comment by jexp** [comment]
you should not use  `-c`    but `-f file`  or `cat file | neo4j-shell` 

`-c`  is for single commands
